### ISSUE TITLE
Consider defining acronym 'IDE' in gettin' giffy with it post

### ISSUE THREAD

**Issue by trashbirdecology** [shannonpileggi/pipinghotdata_distill#1]
Awesome job on [the post](https://www.pipinghotdata.com/posts/2020-09-07-introducing-the-rstudio-ide-and-r-markdown/#ide)! Looks great!

Just a suggestion -- beginners (and beyond) may not know what "IDE" stands for. Consider defining somewhere obvious or removing from the post.

**Comment by shannonpileggi** [comment]
Thanks for the suggestion - done!  Feedback is always welcome.
